# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import education.education_user.models


class Migration(migrations.Migration):

    dependencies = [
        ('education_user', '0002_auto_20180929_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=11, unique=True, validators=[education.education_user.models.is_mobile_phone_number], verbose_name='mobile phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=32, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
