# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-27 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='image_name',
        ),
    ]
