# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerimage',
            name='image_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Image Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Image Name'),
        ),
        migrations.AlterField(
            model_name='exampleimage',
            name='image_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Image Name'),
        ),
    ]
